In [1]:
import pandas as pd

The history saving thread hit an unexpected error (OperationalError('database or disk is full')).History will not be written to the database.

In [2]:
data = pd.read_csv("Pokemon.csv")
data.head(n=10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

# Hp column:

In [3]:
HP_mean = data["HP"].mean()
def set_HP(val):
    if val < HP_mean:
        return "HP Low"
    elif val == HP_mean:
        return "HP neutral"
    else:
        return "HP High"

In [6]:
data["HP_high_low"] = data["HP"].apply(set_HP)
data

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,HP_high_low
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,HP Low
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,HP Low
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,HP High
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,HP High
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,HP Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,HP Low
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,HP Low
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,HP High
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,HP High
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,HP High

In [9]:
Speed_mean = data["Speed"].mean()
def set_Speed(val):
    if val < Speed_mean:
        return "Speed Low"
    elif val == Speed_mean:
        return "Speed neutral"
    else:
        return "Speed High"

In [10]:
data["Speed_High_Low"] = data["Speed"].apply(set_Speed)
data

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,HP_high_low,Speed_High_Low
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,HP Low,Speed Low
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,HP Low,Speed Low
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,HP High,Speed High
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,HP High,Speed High
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,HP Low,Speed Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,HP Low,Speed Low
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,HP Low,Speed High
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,HP High,Speed High
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,HP High,Speed High
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,HP High,Speed High